[package]
name = "sui-rosetta"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum = "0.5.13"
axum-core = "0.2.7"
axum-macros = "0.2.3"
anyhow = { version = "1.0.58", features = ["backtrace"] }
tracing = "0.1.36"
serde = "1.0.143"
serde_json = "1.0.83"
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.4", features = ["cors"] }
tokio = "1.20.1"
once_cell = "1.13.1"
serde_with = "1.14.0"
itertools = "0.10.3"
signature = "1.6.0"
bcs = "0.1.3"
hyper = "0.14.20"
strum = "0.24.1"
strum_macros = "0.24.3"
sha3 = "0.10.2"
async-trait = "0.1.57"
futures = "0.3.24"

telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "d96230a9272c322a7eefac49708aadfff1eed77e" }

sui-types = { path = "../sui-types" }
sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-quorum-driver = { path = "../sui-quorum-driver" }

move-core-types = { git = "https://github.com/move-language/move", rev = "70b34a66473c34ad30d101290b249f2db3c847a2", features = ["address20"] }

typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "d96230a9272c322a7eefac49708aadfff1eed77e"}
typed-store-macros = { git = "https://github.com/MystenLabs/mysten-infra", rev = "d96230a9272c322a7eefac49708aadfff1eed77e"}

workspace-hack = { path = "../workspace-hack"}


