---
version: "3.9"
services:
  rosetta:
    image: mysten/sui-rosetta
    ports:
      - "9002:9002"
      - "9003:9003"
    expose:
      - "9002"
      - "9003"
    volumes:
      - sui:/sui
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/sui start &> /sui/sui.log &
        /usr/local/bin/sui-rosetta start-online-server &> /sui/online.log &
        /usr/local/bin/sui-rosetta start-offline-server &> /sui/offline.log
    stdin_open: true
    tty: true
volumes:
  sui: